class NotificationError(Exception):
    pass


class AlreadySentError(NotificationError):
    pass
